// ========== AUTH ==========
export const REGISTER_REQUEST = "REGISTER_REQUEST";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAILURE = "REGISTER_FAILURE";

export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";

export const NEWPASSWORD_REQUEST = "NEWPASSWORD_REQUEST";
export const NEWPASSWORD_SUCCESS = "NEWPASSWORD_SUCCESS";
export const NEWPASSWORD_FAILURE = "NEWPASSWORD_FAILURE";

// ========== EQUIPMENT ==========
export const EQUIPMENT_CREATE_REQUEST = "EQUIPMENT_CREATE_REQUEST";
export const EQUIPMENT_CREATE_SUCCESS = "EQUIPMENT_CREATE_SUCCESS";
export const EQUIPMENT_CREATE_FAILURE = "EQUIPMENT_CREATE_FAILURE";

export const FETCH_EQUIPMENTS_REQUEST = "FETCH_EQUIPMENTS_REQUEST";
export const FETCH_EQUIPMENTS_SUCCESS = "FETCH_EQUIPMENTS_SUCCESS";
export const FETCH_EQUIPMENTS_FAILURE = "FETCH_EQUIPMENTS_FAILURE";
// ========== BOOKINGS ==========
export const BOOK_EQUIPMENT_REQUEST = "BOOK_EQUIPMENT_REQUEST";
export const BOOK_EQUIPMENT_SUCCESS = "BOOK_EQUIPMENT_SUCCESS";
export const BOOK_EQUIPMENT_FAILURE = "BOOK_EQUIPMENT_FAILURE";

export const CANCEL_BOOKING_REQUEST = "CANCEL_BOOKING_REQUEST";
export const CANCEL_BOOKING_SUCCESS = "CANCEL_BOOKING_SUCCESS";
export const CANCEL_BOOKING_FAILURE = "CANCEL_BOOKING_FAILURE";

export const FETCH_MY_BOOKINGS_REQUEST = "FETCH_MY_BOOKINGS_REQUEST";
export const FETCH_MY_BOOKINGS_SUCCESS = "FETCH_MY_BOOKINGS_SUCCESS";
export const FETCH_MY_BOOKINGS_FAILURE = "FETCH_MY_BOOKINGS_FAILURE";

export const FETCH_LENDER_BOOKINGS_REQUEST = "FETCH_LENDER_BOOKINGS_REQUEST";
export const FETCH_LENDER_BOOKINGS_SUCCESS = "FETCH_LENDER_BOOKINGS_SUCCESS";
export const FETCH_LENDER_BOOKINGS_FAILURE = "FETCH_LENDER_BOOKINGS_FAILURE";

export const MARK_BOOKING_COMPLETED_REQUEST = "MARK_BOOKING_COMPLETED_REQUEST";
export const MARK_BOOKING_COMPLETED_SUCCESS = "MARK_BOOKING_COMPLETED_SUCCESS";
export const MARK_BOOKING_COMPLETED_FAILURE = "MARK_BOOKING_COMPLETED_FAILURE";

